# Generated by Django 3.1.7 on 2021-03-27 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.FloatField()),
                ('city', models.CharField(max_length=50)),
                ('user_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('yearly_income', models.IntegerField()),
                ('description', models.TextField()),
                ('list_date', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 22, 4, 54, 795614))),
            ],
        ),
    ]
